version: "3"
services:
  app:
    container_name: dev_react_movie_service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
    - ./:/var/www
    ports:
    - "3000:3000"
    networks:
    - dev_react_movie_service_network

networks:
  dev_react_movie_service_network:
